# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        DG\InventarioBundle\Entity\UsuarioSistema:
            algorithm:        sha512
            encode-as-base64: true
            iterations:       10
#    role_hierarchy:
#        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]        
    providers:
        user_db:
            entity: { class: DG\InventarioBundle\Entity\UsuarioSistema, property: username }
#        hwi:
#            id: hwi_oauth.user.provider.entity              
        in_memory:
            memory: ~

    firewalls:
        login_:
            pattern:  ^/secured/login$
            security: false
            anonymous: ~
        secured_area:
            anonymous: ~
#            oauth:
#                resource_owners:
#                    facebook:           "/login/check-facebook"
#                login_path:          /secured/login
#                default_target_path: /admin/usuario
#                failure_path:        /secured/login
#
#                oauth_user_provider:
#                    service: hwi_oauth.user.provider.entity
                    
            pattern: ^/
            switch_user: { role: ROLE_ADMIN, parameter: _change }
            form_login:
                login_path: /secured/login
                check_path: /secured/login_check
                default_target_path: /admin/usuario
                #always_use_default_target_path: true 
                failure_path:      /secured/login
                #use_referer:         true
            logout:
                path: /secured/logout
                target: /secured/login        

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/usuario/registeruser/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/usuario/account/created, role: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/admin/*, role:  ROLE_USER } 
        - { path: ^/secured/*, role: IS_AUTHENTICATED_ANONYMOUSLY }
        #Roles admin
        - { path: ^/admin/*, role:  ROLE_ADMIN }
        